### ISSUE TITLE
keyError是什么问题呢？

### ISSUE THREAD

**Issue by 349989153** [qzcool/Tianyancha#42]
输入用户名密码后，显示：

在自动输入完用户名和密码前，请勿操作鼠标键盘！请保持优雅勿频繁（间隔小于1分钟）登录以减轻服务器负载。
请现在开始操作键盘鼠标，在15s内点击登录并手工完成滑块验证码。批量爬取只需一次登录。
还剩5秒。
您的本次登录共用时20秒。
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    tuple_dicts = Tianyancha(username='xxxxxx', password='xxxxxxx').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 435, in tianyancha_scraper_batch
    keyword = df_input['公司名称'].iloc[i]
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d\xe7\xa7\xb0'

**Comment by 349989153** [comment]
请问这是什么问题呢？本人有一点编程基础，但不会py

**Comment by 349989153** [comment]
再请问一下，input.xlsx应该放在哪个路径下，我看文档好像并没有说明

**Comment by 349989153** [comment]
好吧，我把input.xlsx的“公司名称”改成“CompanyName”, tianyancha.py的keyword = df_input['公司名称'].iloc[i] 也改了，可以跑起来了。

**Comment by 349989153** [comment]
然后又有新的问题：


在自动输入完用户名和密码前，请勿操作鼠标键盘！请保持优雅勿频繁（间隔小于1分钟）登录以减轻服务器负载。
请现在开始操作键盘鼠标，在15s内点击登录并手工完成滑块验证码。批量爬取只需一次登录。
还剩5秒。
您的本次登录共用时19秒。
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    tuple_dicts = Tianyancha(username='15201458525', password='sJ31320456').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 442, in tianyancha_scraper_batch
    table_dict = self.tianyancha_scraper(keyword=keyword, table=tables, change_page_interval=change_page_interval, export=export, quit_driver=False)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 414, in tianyancha_scraper
    self.driver = search_company(self.driver, url_search)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 132, in search_company
    soup1 = BeautifulSoup(content, 'lxml')
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 208, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
luyangdeMacBook-Pro:tyc luyang$

**Comment by 349989153** [comment]
ok，我安装了lxml，然后又有新的问题：


在自动输入完用户名和密码前，请勿操作鼠标键盘！请保持优雅勿频繁（间隔小于1分钟）登录以减轻服务器负载。
请现在开始操作键盘鼠标，在15s内点击登录并手工完成滑块验证码。批量爬取只需一次登录。
还剩5秒。
您的本次登录共用时19秒。
登陆成功。
正在爬取baseInfo
baseInfo表格为特殊格式，使用了标准表格爬取函数。
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    tuple_dicts = Tianyancha(username='xxx', password='xxx').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 442, in tianyancha_scraper_batch
    table_dict = self.tianyancha_scraper(keyword=keyword, table=tables, change_page_interval=change_page_interval, export=export, quit_driver=False)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 415, in tianyancha_scraper
    table_dict = scrapy(self.driver, table, use_default_exception)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 358, in scrapy
    table_dict[name[x]] = get_base_info(driver)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 156, in get_base_info
    base_table['电话'] = base_info.text.split('电话：')[1].split('邮箱：')[0].split('查看')[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

**Comment by 349989153** [comment]
好的，我把我的py文件改成：

from tianyancha import Tianyancha
import sys
defaultencoding = 'utf-8'
if sys.getdefaultencoding() != defaultencoding:
    reload(sys)
    sys.setdefaultencoding(defaultencoding)

tuple_dicts = Tianyancha(username='xxx', password='xxx').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
tuple_dicts[0]

然后解决了这个问题

**Comment by 349989153** [comment]
然后又遇到新的问题：


在自动输入完用户名和密码前，请勿操作鼠标键盘！请保持优雅勿频繁（间隔小于1分钟）登录以减轻服务器负载。
请现在开始操作键盘鼠标，在15s内点击登录并手工完成滑块验证码。批量爬取只需一次登录。
还剩5秒。
您的本次登录共用时19秒。
登陆成功。
正在爬取baseInfo
正在爬取staff
没有翻页
没有时间切换页
正在爬取holder
没有翻页
没有时间切换页
正在爬取changeinfo
没有时间切换页
正在爬取branch
没有翻页
没有时间切换页
Traceback (most recent call last):
  File "index.py", line 8, in <module>
    tuple_dicts = Tianyancha(username='xxx', password='xxx').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 442, in tianyancha_scraper_batch
    table_dict = self.tianyancha_scraper(keyword=keyword, table=tables, change_page_interval=change_page_interval, export=export, quit_driver=False)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 417, in tianyancha_scraper
    gen_excel(table_dict, keyword)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 399, in gen_excel
    with pd.ExcelWriter(keyword+'.xlsx') as writer:
  File "/usr/local/lib/python2.7/site-packages/pandas/io/excel.py", line 1204, in __init__
    from openpyxl.workbook import Workbook
ImportError: No module named openpyxl.workbook

**Comment by 349989153** [comment]
然后pip install openpyxl，把这个包装上了，又有其他的问题：

您的本次爬取共用时6秒。
登陆成功。
正在爬取baseInfo
baseInfo表格为特殊格式，使用了标准表格爬取函数。
Traceback (most recent call last):
  File "index.py", line 8, in <module>
    tuple_dicts = Tianyancha(username='xxx', password='xxx').tianyancha_scraper_batch(input_template='input.xlsx', export='xlsx')
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 442, in tianyancha_scraper_batch
    table_dict = self.tianyancha_scraper(keyword=keyword, table=tables, change_page_interval=change_page_interval, export=export, quit_driver=False)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 415, in tianyancha_scraper
    table_dict = scrapy(self.driver, table, use_default_exception)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 358, in scrapy
    table_dict[name[x]] = get_base_info(driver)
  File "/usr/local/lib/python2.7/site-packages/tianyancha/tianyancha.py", line 179, in get_base_info
    rows2 = tabs[1].find_elements_by_tag_name('tr')
IndexError: list index out of range
